Repository civisanalytics/civis-python, pull requests merged in 2018-04, with the labels that each got.

#248 BUG Fix tests in test_io
  CHANGELOG.md
  civis/tests/test_io.py
Labels: Testing, bug

#250 DOC Surface civis.find and civis.find_one in the Sphinx docs
  CHANGELOG.md
  civis/civis.py
  docs/source/conf.py
  docs/source/index.rst
  docs/source/parallel.rst
  docs/source/responses.rst
  docs/source/user_guide.rst
Labels: Documentation

#247 ENH Add CivisML v2.2 template IDs
  CHANGELOG.md
  civis/ml/_model.py
  civis/ml/tests/test_model.py
Labels: Modeling, enhancement

#251 MAINT Update version number to 1.9.0
  CHANGELOG.md
  civis/_version.py
Labels: Maintenance
