Repository civisanalytics/civis-python, pull requests merged in 2018-02, with the labels that each got.

#224 DOC Document civis.find and civis.find_one
  CHANGELOG.md
  civis/civis.py
  dev-requirements.txt
Labels: Documentation

#225 ENH Public schema/tablename-splitting function
  CHANGELOG.md
  civis/civis.py
  civis/io/_tables.py
  civis/tests/test_io.py
Labels: I/O, enhancement

#229 MAINT Add changelog rule to gitattributes
  .gitattributes
  CHANGELOG.md
Labels: Maintenance

#231 DOC: Adding missing function documentation
  CHANGELOG.md
  docs/source/io.rst
Labels: Documentation, bug

#236 ENH Include parent job and run ID in children
  CHANGELOG.md
  civis/futures.py
  civis/parallel.py
  civis/tests/test_futures.py
  docs/source/parallel.rst
Labels: enhancement
