Repository civisanalytics/civis-python, pull requests merged in 2018-03, with the labels that each got.

#239 DOC clarify when non-sklearn estimators used in CivisML
  CHANGELOG.md
  docs/source/ml.rst
Labels: Documentation

#241 ENH Add "dvs_to_predict" param to ModelPipeline.predict
  CHANGELOG.md
  civis/ml/_model.py
Labels: Modeling, enhancement

#238 Adding export_to_civis_file
  CHANGELOG.md
  civis/io/_tables.py
  civis/tests/test_io.py
  docs/source/io.rst
Labels: I/O, enhancement

#244 BUG Include JSONs in package data
  CHANGELOG.md
  setup.py
Labels: bug

#243 default to "all" resources
  CHANGELOG.md
  civis/_deprecation.py
  civis/civis.py
  civis/futures.py
  civis/io/_databases.py
  civis/io/_files.py
  civis/io/_tables.py
  civis/ml/_model.py
  civis/parallel.py
  civis/resources/_resources.py
  civis/tests/mocks.py
  civis/tests/test_deprecate.py
  civis/utils/_jobs.py
  docs/source/conf.py
  docs/source/user_guide.rst
  tools/smoke_tests.py
Labels: Deprecation

#246 In Which We Flush Buffers After Finishing Writing to Them
  CHANGELOG.md
  civis/io/_files.py
Labels: I/O, bug

#240 DOC Update max_depth settings for CivisML
  CHANGELOG.md
  docs/source/ml.rst
Labels: Documentation

#242 ENH Register models trained outside of Civis Platform
  civis/ml/_model.py
  civis/ml/tests/test_model.py
  docs/source/ml.rst
Labels: Modeling, enhancement
