Repository civisanalytics/civis-python, pull requests merged in 2019-08, with the labels that each got.

#314 ENH helper function to list models
  CHANGELOG.md
  civis/ml/__init__.py
  civis/ml/_helper.py
  civis/ml/tests/test_helper.py
Labels: enhancement

#316 BUG Use APIClient method name parsing for CLI
  CHANGELOG.md
  civis/cli/__main__.py
  civis/tests/test_cli.py
Labels: CLI, bug

#320 DOC: Adding missing docs to sphinx
  CHANGELOG.md
  docs/source/io.rst
Labels: Documentation, bug

#318 [SERD-1446] ENH Added run_template function
  CHANGELOG.md
  civis/tests/test_jobs.py
  civis/utils/__init__.py
  civis/utils/_jobs.py
  docs/source/index.rst
  docs/source/utils.rst
Labels: enhancement
