Repository civisanalytics/civis-python, pull requests merged in 2019-02, with the labels that each got.

#281 TST update test api specs
  CHANGELOG.md
  civis/tests/civis_api_spec.json
  civis/tests/civis_api_spec_channels.json
  civis/tests/test_cli.py
Labels: Testing

#282 MAINT increment to V1.9.3
  CHANGELOG.md
  civis/_version.py
Labels: Maintenance

#285 FIX get_table_id should correctly handle quoted schema.tablename
  CHANGELOG.md
  civis/civis.py
  civis/tests/test_civis.py
Labels: bug

#288 bump version and update changelog for v1.9.4
  CHANGELOG.md
  civis/_version.py
Labels: Maintenance
