Repository civisanalytics/civis-python, pull requests merged in 2019-06, with the labels that each got.

#299 Compatibility with joblib > 0.11
  CHANGELOG.md
  civis/parallel.py
  civis/tests/test_parallel.py
  requirements.txt
  setup.py
Labels: Maintenance

#303 BUG Fix unintentional dependency on scikit-learn for testing
  CHANGELOG.md
  civis/parallel.py
Labels: Testing, bug

#300 MAINT Relax requirements on click and jsonschema
  CHANGELOG.md
  requirements.txt
  setup.py
Labels: Maintenance

#305 ENH utils module available from civis namespace
  CHANGELOG.md
  civis/__init__.py
Labels: enhancement

#304 ENH dataframe and json to-file conveniences
  CHANGELOG.md
  civis/io/_files.py
Labels: I/O, enhancement

#301 ENH Include Python version in User-Agent string
  CHANGELOG.md
  civis/_utils.py
Labels: enhancement

#302 ENH last_response attribute for the APIClient
  CHANGELOG.md
  civis/base.py
  civis/civis.py
  civis/tests/test_base.py
Labels: enhancement

#309 MAINT Restrict cloudpickle version in Python 3.4
  CHANGELOG.md
  requirements.txt
  setup.py
Labels: Maintenance

#310 TST Test in Xenial environment
  .travis.yml
  CHANGELOG.md
Labels: Testing

#311 COMPAT Deprecation decorator takes multiple parameter names
  CHANGELOG.md
  civis/_deprecation.py
  civis/tests/test_deprecate.py
Labels: Maintenance, enhancement

#307 DEP Deprecate headers parameter of dataframe_to_civis
  CHANGELOG.md
  civis/io/_tables.py
Labels: Deprecation, I/O, bug

#312 Allow changing log level & base URL for CLI with environment variables
  CHANGELOG.md
  civis/cli/__main__.py
Labels: enhancement
