Repository civisanalytics/civis-python, pull requests merged in 2020-01, with the labels that each got.

#341 [PARO-685] [PARO-744] Decouple CivisML from civis-python: Use template ID aliases and move docs to Zendesk
  CHANGELOG.md
  civis/ml/_helper.py
  civis/ml/_model.py
  civis/ml/tests/test_helper.py
  civis/ml/tests/test_model.py
  docs/source/ml.rst
Labels: Documentation, Modeling, enhancement

#347 [PARO-685] Smoke tests for different CivisML alias objects
  CHANGELOG.md
  civis/ml/_model.py
  tools/smoke_tests.py
Labels: Modeling, Testing, bug

#349 MAINT update dependencies for CivisML
  CHANGELOG.md
  requirements.txt
  setup.py
Labels: Maintenance, Modeling
