Repository civisanalytics/civis-python, pull requests merged in 2020-03, with the labels that each got.

#367 Add follow-logs documentation to the big CLI docs
  CHANGELOG.md
  README.rst
  docs/source/cli.rst
Labels: Documentation

#365 account for when n_jobs is none
  CHANGELOG.md
  civis/parallel.py
Labels: bug

#369 bug with from_existing
  CHANGELOG.md
  civis/ml/_model.py
  civis/ml/tests/test_model.py
Labels: bug

#368 Add changelog for hidden param fix (#364)
  CHANGELOG.md
Labels: Documentation

#371 Speed up repeated invocations of create_client_mock
  CHANGELOG.md
  civis/tests/mocks.py
Labels: Performance, Testing

#377 Fixed/relaxed version specifications for click, jsonref, and jsonschema.
  CHANGELOG.md
  requirements.txt
  setup.py
Labels: Dependencies
