Repository civisanalytics/civis-python, pull requests merged in 2021-12, with the labels that each got.

#438 [CIVIS-1614] DOC specify response type in Returns documentation.
  CHANGELOG.md
  civis/resources/_resources.py
  civis/tests/test_resources.py
Labels: Documentation

#437 [APIC-66] ENH add job and run IDs as custom headers in API calls
  CHANGELOG.md
  civis/_utils.py
Labels: enhancement

#440 [CIVIS-1775] MAINT update `civis_api_spec.json`
  CHANGELOG.md
  README.rst
  civis/resources/__init__.py
  civis/resources/_resources.py
  civis/resources/civis_api_spec.json
  civis/tests/__init__.py
  civis/tests/civis_api_spec.json
  civis/tests/mocks.py
  civis/tests/test_civis.py
  civis/tests/test_cli.py
  civis/tests/test_client.py
  civis/tests/test_futures.py
  civis/tests/test_io.py
  civis/tests/test_resources.py
  docs/source/conf.py
  tools/update_civis_api_spec_json.py
Labels: Maintenance

#441 [CIVIS-1775] FIX updated location of `civis_api_spec.json` in `setup py`
  CHANGELOG.md
  setup.py
Labels: bug

#442 [CIVIS-1787] DOC show details for multi-word API endpoints in Sphinx docs
  CHANGELOG.md
  civis/io/_tables.py
  civis/resources/_resources.py
  civis/tests/test_resources.py
  docs/source/conf.py
  docs/source/user_guide.rst
Labels: Documentation

#443 [CIVIS-1510] DOC call out `joblib.Parallel`'s `pre_dispatch`
  CHANGELOG.md
  docs/source/parallel.rst
Labels: Documentation

#444 [CIVIS-1851] DOC update info about MacOS shell config file
  CHANGELOG.md
  README.rst
  examples/PythonAPIClientDemo.ipynb
Labels: Documentation

#445 [CIVIS-1509] DOC improve documentation of input to `civis.io.civis_file_to_table`
  CHANGELOG.md
  civis/io/_tables.py
Labels: Documentation

#446 [CIVIS-1678] MAINT turn on security checks with `safety` and `bandit`
  .circleci/config.yml
  CHANGELOG.md
  civis/_utils.py
  civis/io/_files.py
  civis/io/_tables.py
  civis/parallel.py
  civis/run_joblib_func.py
Labels: Security

#447 [CIVIS-1630] DOC document best practices for testing
  .gitignore
  CHANGELOG.md
  docs/source/user_guide.rst
Labels: Documentation

#439 [CIVP-24576] FIX relax SQL type checking in `civis_file_to_table`
  CHANGELOG.md
  civis/io/_tables.py
  civis/tests/test_io.py
Labels: bug

#448 [CIVIS-1835] VER v1.16.0 release
  CHANGELOG.md
  civis/_version.py
Labels: Maintenance
