Repository civisanalytics/civis-python, pull requests merged in 2021-11, with the labels that each got.

#427 [APIC-309] [APIC-317] DOC clarify `buf` and `expires_at` for Civis file functions
  CHANGELOG.md
  civis/io/_files.py
Labels: Documentation

#429 [CIVIS-1508] DEP upgrade joblib dep
  CHANGELOG.md
  requirements.txt
  setup.py
Labels: Dependencies

#426 [CIVP-19775] ENH add job and run ID to CivisJobFailure from CivisFuture
  CHANGELOG.md
  civis/base.py
  civis/futures.py
  civis/ml/tests/test_model.py
  civis/polling.py
  civis/tests/mocks.py
  civis/tests/test_futures.py
Labels: enhancement

#428 [CIVP-22464] BUG Better error message when CSV preprocessing fails in `civis_file_to_table`
  CHANGELOG.md
  civis/io/_tables.py
Labels: bug

#431 [CIVIS-1642] FIX deprecate the inactive `retry_total` parameter of `civis.APIClient`
  CHANGELOG.md
  civis/civis.py
Labels: bug

#430 [CIVIS-1609] FIX no `assert` statements in non-test code
  CHANGELOG.md
  civis/base.py
  civis/civis.py
  civis/cli/__main__.py
  civis/cli/_cli_commands.py
  civis/resources/_resources.py
  civis/response.py
Labels: bug

#433 [CIVIS-1656] DOC update `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: Documentation

#434 [APIC-280] DOC clarify table_columns param in civis.io functions
  civis/io/_tables.py
Labels: Documentation

#435 [CIVIS-1609] FIX remove more `assert` statements
  CHANGELOG.md
  civis/io/_tables.py
Labels: bug

#432 [CIVIS-1640] MAINT switch from TravisCI to CircleCI
  .circleci/config.yml
  .github/pull_request_template.md
  .travis.yml
  CHANGELOG.md
  README.rst
  dev-requirements.txt
  docs/source/conf.py
Labels: Maintenance

#436 [CIVIS-1508] DEP support Python 3.9, drop 3.6, bump other dep version numbers
  .circleci/config.yml
  CHANGELOG.md
  README.rst
  dev-requirements.txt
  docs/source/index.rst
  requirements.txt
  setup.py
Labels: Dependencies

#415 [CIVP-24324] FIX remove `_get_headers` in `read_civis_sql`
  CHANGELOG.md
  civis/io/_tables.py
  civis/tests/cassettes/ImportTests.test_read_civis_no_pandas.yml
  civis/tests/cassettes/ImportTests.test_read_civis_pandas.yml
  civis/tests/cassettes/ImportTests.test_read_civis_sql.yml
  civis/tests/test_io.py
Labels: bug, Refactor
